# Generated by Django 3.0.3 on 2020-02-23 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payor_Payee',
            fields=[
                ('payor_payee_id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payee',
            fields=[
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='exactuals.User')),
                ('preference', models.CharField(max_length=100)),
                ('receive_payment_method', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Payor',
            fields=[
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='exactuals.User')),
                ('send_payment_method', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=20, unique=True)),
                ('bath_id', models.CharField(max_length=20, unique=True)),
                ('date', models.DateTimeField(verbose_name='Transaction Date')),
                ('disbursement', models.CharField(max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('trans_type', models.CharField(max_length=20)),
                ('timezone', models.CharField(max_length=10)),
                ('status', models.CharField(max_length=20)),
                ('status_date', models.DateTimeField(verbose_name='Transaction Status Date')),
                ('payor_payee_id', models.OneToOneField(on_delete=models.SET('Payor_payee removed'), to='exactuals.Payor_Payee')),
            ],
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_num', models.IntegerField()),
                ('rounting_num', models.IntegerField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exactuals.User')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=100)),
                ('street_2', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('zipcode', models.IntegerField()),
                ('country', models.CharField(max_length=30)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exactuals.User')),
            ],
        ),
        migrations.AddField(
            model_name='payor_payee',
            name='payee_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='exactuals.Payee'),
        ),
        migrations.AddField(
            model_name='payor_payee',
            name='payor_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='exactuals.Payor'),
        ),
    ]
