# Generated by Django 3.0.3 on 2020-02-23 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exactuals', '0002_auto_20200223_0517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='exactuals.User'),
        ),
    ]
