# Generated by Django 3.0.3 on 2020-03-07 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exactuals', '0004_auto_20200225_0432'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='bath_id',
        ),
        migrations.AddField(
            model_name='payee',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payor',
            name='id',
            field=models.AutoField(auto_created=True, default=2, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payor_payee',
            name='id',
            field=models.AutoField(auto_created=True, default=3, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='batch_id',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='memo',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='passworld',
            field=models.CharField(default=4, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payee',
            name='user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='exactuals.User'),
        ),
        migrations.AlterField(
            model_name='payor',
            name='user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='exactuals.User'),
        ),
        migrations.AlterField(
            model_name='payor_payee',
            name='payor_payee_id',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
