# Generated by Django 3.0.3 on 2020-03-07 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exactuals', '0005_auto_20200307_0046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='passworld',
            new_name='password',
        ),
    ]
