# Generated by Django 3.0.4 on 2020-03-07 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exactuals', '0007_auto_20200306_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='payor_payee_id',
            field=models.ForeignKey(on_delete=models.SET('Payor_payee removed'), to='exactuals.Payor_Payee'),
        ),
    ]
