# Generated by Django 3.0.4 on 2020-03-09 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exactuals', '0009_auto_20200306_1709'),
        ('exactuals', '0009_auto_20200307_0110'),
    ]

    operations = [
    ]
