# Generated by Django 3.0.4 on 2020-03-10 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exactuals', '0010_merge_20200309_2225'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='user_id',
            new_name='uid',
        ),
        migrations.RenameField(
            model_name='bank',
            old_name='user_id',
            new_name='uid',
        ),
        migrations.RenameField(
            model_name='payee',
            old_name='user_id',
            new_name='uid',
        ),
        migrations.RenameField(
            model_name='payor',
            old_name='user_id',
            new_name='uid',
        ),
        migrations.RenameField(
            model_name='payor_payee',
            old_name='payor_payee_id',
            new_name='ppid',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='batch_id',
            new_name='bid',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='payor_payee_id',
            new_name='ppid',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='transaction_id',
            new_name='tid',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_id',
            new_name='uid',
        ),
    ]
