# Generated by Django 3.0.4 on 2020-04-14 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exactuals', '0013_auto_20200310_0428'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(default='payor', max_length=10),
            preserve_default=False,
        ),
    ]
