# Generated by Django 3.0.4 on 2020-04-14 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exactuals', '0014_user_user_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='payor',
            unique_together={('id', 'uid')},
        ),
    ]
