# Generated by Django 3.0.4 on 2020-04-15 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exactuals', '0015_auto_20200414_2218'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='payor',
            unique_together=set(),
        ),
    ]
