# Generated by Django 3.0.4 on 2020-04-15 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exactuals', '0017_auto_20200415_0353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payee',
            name='uid',
            field=models.OneToOneField(db_column='uid', on_delete=django.db.models.deletion.CASCADE, to='exactuals.User'),
        ),
        migrations.AlterField(
            model_name='payor',
            name='uid',
            field=models.OneToOneField(db_column='uid', on_delete=django.db.models.deletion.CASCADE, to='exactuals.User'),
        ),
        migrations.AlterField(
            model_name='payor_payee',
            name='payee_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exactuals.Payee'),
        ),
        migrations.AlterField(
            model_name='payor_payee',
            name='payor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exactuals.Payor'),
        ),
    ]
