# Generated by Django 3.0.6 on 2020-05-12 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exactuals', '0020_auto_20200415_0424'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='bank_name',
            field=models.CharField(default='none', max_length=50),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('transaction_status', models.BooleanField()),
                ('transaction_cost', models.DecimalField(decimal_places=2, max_digits=14)),
                ('transaction_state_date', models.DateTimeField()),
                ('transaction_end_date', models.DateTimeField()),
                ('transaction_revenue', models.BooleanField()),
                ('processor_type', models.IntegerField(choices=[(1, 'A'), (2, 'B'), (3, 'C')])),
                ('country', models.IntegerField(choices=[(410, 'Kor'), (156, 'Chn'), (840, 'Usa'), (250, 'Fra'), (76, 'Bra'), (276, 'Deu'), (484, 'Mex'), (356, 'Ind')])),
                ('original_currency', models.IntegerField(choices=[(1, 'A'), (2, 'B'), (3, 'C')])),
                ('target_currency', models.IntegerField(choices=[(1, 'A'), (2, 'B'), (3, 'C')])),
                ('fx', models.BooleanField()),
                ('payee_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='exactuals.Payee')),
                ('payor_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='exactuals.Payor')),
                ('ppid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='exactuals.Payor_Payee')),
            ],
        ),
    ]
