# Generated by Django 3.0.6 on 2020-05-12 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exactuals', '0021_auto_20200512_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='original_currency',
            field=models.IntegerField(choices=[(410, 'Krw'), (156, 'Cny'), (840, 'Usd'), (978, 'Eur'), (986, 'Brl'), (484, 'Mxn'), (356, 'Inr')]),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='target_currency',
            field=models.IntegerField(choices=[(410, 'Krw'), (156, 'Cny'), (840, 'Usd'), (978, 'Eur'), (986, 'Brl'), (484, 'Mxn'), (356, 'Inr')]),
        ),
    ]
