# Generated by Django 3.0.6 on 2020-05-12 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exactuals', '0022_auto_20200512_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('Payor', 'Pyr'), ('Payee', 'Pye')], max_length=10),
        ),
    ]
