# Generated by Django 3.0.6 on 2020-05-14 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exactuals', '0023_auto_20200512_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='overall_satisfaction',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='payee_satisfaction',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='payor_satisfaction',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Transaction Status Date'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='bank_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='transaction_end_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='transaction_state_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='transaction_status',
            field=models.BooleanField(null=True),
        ),
    ]
