# Generated by Django 3.0.6 on 2020-05-14 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exactuals', '0024_auto_20200514_0023'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='payor_payee_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='exactuals.Payor_Payee'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdata',
            name='pye_id',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdata',
            name='pyr_id',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userdata',
            name='ppid',
            field=models.IntegerField(blank=True),
        ),
    ]
