# Generated by Django 3.0.6 on 2020-05-14 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exactuals', '0025_auto_20200514_0152'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdata',
            old_name='processor_type',
            new_name='processor',
        ),
        migrations.RenameField(
            model_name='userdata',
            old_name='transaction_state_date',
            new_name='transaction_start_date',
        ),
    ]
