# Generated by Django 3.0.4 on 2020-06-04 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exactuals', '0026_auto_20200514_0519'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdata',
            old_name='transaction_cost',
            new_name='transaction_profit',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='transaction_revenue',
        ),
    ]
