# Generated by Django 3.0.4 on 2020-06-05 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exactuals', '0027_auto_20200604_0553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('PYR', 'Pyr'), ('PYE', 'Pye')], max_length=10),
        ),
    ]
