# Generated by Django 3.0.4 on 2020-06-07 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exactuals', '0028_auto_20200605_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='payor_payee',
            name='feedback_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='payor_payee',
            name='satisfaction',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='transaction',
            name='processor',
            field=models.IntegerField(choices=[(1, 'A'), (2, 'B'), (3, 'C')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='satisfaction',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('Payor', 'Pyr'), ('Payee', 'Pye')], max_length=10),
        ),
    ]
