# Generated by Django 3.0.4 on 2020-06-07 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exactuals', '0029_auto_20200607_0622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payor_payee',
            name='satisfaction',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='satisfaction',
            field=models.IntegerField(null=True),
        ),
    ]
